# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath

# networks:
#   default: hardhat

dependencies: 
  - OpenZeppelin/openzeppelin-contracts@4.8.0

compiler:
  solc:
    version: null
    remappings: 
      # -@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0'
  vyper:
    version: null

autofetch_sources: true
dev_deployment_artifacts: true

dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}

